#server:
#  port: 8082
#
#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
#
#  datasource:
#    url: jdbc:mariadb://astar-maria.c5dsp2ro13rz.ap-northeast-2.rds.amazonaws.com:3306/taehan
#    username: astar6
#    password: dktmxkzjavjsl*6
#    driver-class-name: org.mariadb.jdbc.Driver
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: jangm0611@gmail.com
#    password: tijstxbvdjlwvcal
#    properties:
#      mail:
#        smtp:
#          auth: true
#          timeout: 5000
#          starttls:
#            enable: true
#
#mybatis:
#  mapper-locations: classpath:com.example.crud.repository/*.xml
#  config-location: classpath:mybatis-config.xml
#  type-aliases-package: com.example.crud.domain
